version: '3.7'

services:
    tailwindcss:
        container_name: 'tailwindcss_container'
        build: .
        restart: unless-stopped
        ports:
            - '8181:8181'
        volumes:
            - './src:/var/www'
        working_dir: /var/www
        command: bash -c "npm run dev"
        networks:
            - web
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.whoami.rule=Host(`tailwindcss.dv`)'
            - 'traefik.http.routers.whoami.entrypoints=websecure'
            - 'traefik.http.routers.whoami.tls.domains[0].main=tailwindcss.dv'

networks:
    web:
        external: true
